### ISSUE TITLE
Is this project alive or dead?

### ISSUE THREAD

**Issue by rap2hpoutre** [patosmack/laravel-excel#2]

**Comment by richardkeep** [comment]
Co-ask. I am looking for a Laravel Excel Package that can handle imports. Did you get one?

**Comment by patosmack** [comment]
This project its a fork from https://github.com/Cyber-Duck/laravel-excel with a custom modification was generating issues while opening big excels.

**Comment by rap2hpoutre** [comment]
@richardkeep & @richardkeep Without response, I created one too: https://github.com/rap2hpoutre/fast-excel. Feel free to use it (it seems more "alive" that the other one)

**Comment by patosmack** [comment]
thanks @rap2hpoutre ill also check it out

**Comment by richardkeep** [comment]
Thanks @rap2hpoutre .  Just noticed it too, I hope you will be alive for long to maintain it since the rest seem dormant. :)
